version: "3"

#
# run with 
#   docker-compose -f docker-compose-scale.yml --compatibility up --build
#
services:
  wildfly:
    build:
      context: ./wildfly
    ports: 
     - "8081-8091:8080"
     - "9991-10001:9990"
    deploy:
      mode: replicated
      replicas: 3
  load-balancer:
    build:
      context: ./wildfly-load-balancer
    ports:
    - 8080:8080
    - 8090:8090
    - 9990:9990